include:
  - ../database/compose-db.yml

services:
  landscape-ui:
    image: 'emmanuelu17/landscape:latest'
    container_name: landscape-ui
    restart: always
    ports:
      - ${LANDSCAPE_UI_PORT}:80
    networks:
      - landscape-network

  landscape-api:
    image: 'emmanuelu17/landscape-api:latest'
    container_name: landscape-api
    restart: always
    env_file:
      - ../.env
    ports:
      - ${LANDSCAPE_API_PORT}:80
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - db-network
      - landscape-network
    environment:
      SERVER_PORT: ${LANDSCAPE_API_PORT}
      API_PREFIX: 'api/v1/'
      SPRING_DATASOURCE_URL: ${LANDSCAPE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      API_CORS_DOMAIN: ${LANDSCAPE_API_CORS_DOMAIN}
      GOOGLE_CLIENT_ID: 'google-client-id'
      GOOGLE_CLIENT_SECRET: 'google-client-secret'
      APPLICATION_LOG_WEBHOOK_DISCORD: 'discord-webhook'
      SPRING_MAIL_USERNAME: 'mail-username'
      SPRING_MAIL_PASSWORD: 'mail-password'
      SPRING_MAIL_OWNER: 'mail-owner'
      APPLICATION_DOMAIN: ${LANDSCAPE_APPLICATION_DOMAIN}
      APPLICATION_DEVELOPER_EMAIL: 'example@email.com'
      APPLICATION_DEVELOPER_DOMAIN: 'domain.com'

networks:
  db-network:
    name: db-network
  landscape-network:
    name: landscape-network