version: '3.8'
services:
  
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80" # http
      - "443:443" # https
    volumes:
      - ./certs:/etc/nginx/ssl/certs
      - ./private:/etc/nginx/ssl/private
      - ./.nginx/sites-available:/etc/nginx/sites-available/
      - ./.nginx/sites-enabled:/etc/nginx/sites-enabled/
    networks:
      - nginx_network

networks:
  nginx_network: {}
    #external: true
